development:
  host_setting: host_development_value
  _secure_host_secure_setting: NX/tDw5KDxgiGOQYwiTcgc4q9hJPen3qpvkVqZYyWXfA7lgzXann2ipO2LOV2klSdY2bR+xAOr9lWj6ekgj4Xav78mjwJHj/J4t/qPwYNnExB8xpIOMW+lsfcv0j3wSsPdHSaqErKBVCUOf3W37BpMOjhYwkXDbTqe44r7x8T6+MjDFmOGzIxpWsXmE9wqT9uTbWCiAOB7gUEyjsAo54l0crJBU2/comYCdbG4Ttwwgbt/NSuCbo4fdVsMInkXyM98gnRc2QdnF5HYJH3X514fd7O6cDmcW1rTCNzRkav23zYitIeG1ZaWbKCOKXFkOsP0NQXYhJuq/XTk2OOCUTNQ==
