development:
  setting: development_value
  _secure_secure_setting: aod8O9O+ycaOqdgsK6+RNMDNJNXG6MlNCnn7FMKMjKY+7/zrZKVtzbPERM+AMoc3VhpK7Vko8pwDwP0YCYlZvtvNfkaOA6a9cslHvt+mNpIIaSoMc2BfKoqfLWNS3NhQodFJa2tiHNyOQgtvF5u9zvwXtXncoKU8y73zcH8BK42KLuJvfjJ/YhQZjIosFDKpGytPWISimMZGAJgT1f7sIFpRfkGKcOirock/MyxIKwpm2YF0sN9nSbiWiAs28Q0yFFrm1AEBTbBHAIoVvQzrpKIoVRfHjhrb/RaUyguJRX8UQKVGJO+dzHccJYkSF5yo07KZh6C23yABtHqQz07Cdw==
